import type { LayerCategory, LayerConfig } from "../types/globe";

export const ALL_LAYERS: LayerConfig[] = [
  // Base
  {
    id: "blank",
    label: "ไม่มี (โลกเปล่า)",
    chipClass: "chip-blank",
    color: "#2a3555",
    gradientColors: ["#1a2035", "#2a3555"],
    minLabel: "",
    maxLabel: "",
  },
  {
    id: "terrain",
    label: "ภูมิประเทศ",
    chipClass: "chip-terrain",
    color: "#38B56A",
    gradientColors: ["#5B4A2E", "#7A6040", "#38B56A", "#2E8B57", "#1a5c38"],
    minLabel: "ทะเลทราย",
    maxLabel: "ป่า",
  },
  {
    id: "elevation",
    label: "ระดับความสูง",
    chipClass: "chip-elevation",
    color: "#35C3B2",
    gradientColors: ["#0B3D91", "#35C3B2", "#5DE05D", "#F2C94C", "#E25A5A"],
    minLabel: "ระดับน้ำทะเล",
    maxLabel: "8,849 ม.",
  },
  // Environment
  {
    id: "rainfall",
    label: "ปริมาณฝน",
    chipClass: "chip-rainfall",
    color: "#3A87FF",
    gradientColors: ["#F0F4FF", "#A8C8FF", "#3A87FF", "#1A5FCC", "#0B3080"],
    minLabel: "0 มม.",
    maxLabel: "3,000 มม.",
  },
  {
    id: "temperature",
    label: "อุณหภูมิ",
    chipClass: "chip-temperature",
    color: "#FF8A3D",
    gradientColors: ["#0B3D91", "#35C3B2", "#F2C94C", "#FF8A3D", "#E25A5A"],
    minLabel: "-40°C",
    maxLabel: "50°C",
  },
  {
    id: "humidity",
    label: "ความชื้น",
    chipClass: "chip-humidity",
    color: "#67D5FF",
    gradientColors: ["#FFF8E1", "#B3E5FC", "#67D5FF", "#0288D1", "#01579B"],
    minLabel: "0%",
    maxLabel: "100%",
  },
  {
    id: "wind_speed",
    label: "ความเร็วลม",
    chipClass: "chip-wind",
    color: "#B0BEC5",
    gradientColors: ["#E0E0E0", "#B0BEC5", "#607D8B", "#37474F", "#1a252c"],
    minLabel: "0 กม./ชม.",
    maxLabel: "200 กม./ชม.",
  },
  {
    id: "sea_level_risk",
    label: "ความเสี่ยงจากระดับน้ำทะเลขึ้น",
    chipClass: "chip-sealevel",
    color: "#00BCD4",
    gradientColors: ["#F9FBE7", "#C8E6C9", "#00BCD4", "#0097A7", "#006064"],
    minLabel: "ต่ำ",
    maxLabel: "วิกฤต",
  },
  {
    id: "wildfire",
    label: "ความถี่ของไฟป่า",
    chipClass: "chip-wildfire",
    color: "#FF6D00",
    gradientColors: ["#FFF9C4", "#FFD54F", "#FF6D00", "#BF360C", "#4E342E"],
    minLabel: "น้อย",
    maxLabel: "บ่อย",
  },
  {
    id: "deforestation",
    label: "อัตราการตัดไม้ทำลายป่า",
    chipClass: "chip-deforestation",
    color: "#8D6E63",
    gradientColors: ["#1B5E20", "#388E3C", "#AED581", "#A1887F", "#4E342E"],
    minLabel: "คงที่",
    maxLabel: "วิกฤต",
  },
  {
    id: "soil_quality",
    label: "คุณภาพดิน",
    chipClass: "chip-soil",
    color: "#A1887F",
    gradientColors: ["#BF360C", "#8D6E63", "#A1887F", "#C8A97E", "#4CAF50"],
    minLabel: "แย่",
    maxLabel: "ดี",
  },
  // Demographics
  {
    id: "population",
    label: "ความหนาแน่นประชากร",
    chipClass: "chip-population",
    color: "#FF5C7A",
    gradientColors: ["#FFF0D0", "#FFB347", "#FF8C00", "#FF5C7A", "#8B0000"],
    minLabel: "0/กม.²",
    maxLabel: "10,000+/กม.²",
  },
  {
    id: "urban_rural",
    label: "เขตเมืองเทียบกับชนบท",
    chipClass: "chip-urban",
    color: "#AB47BC",
    gradientColors: ["#E8F5E9", "#A5D6A7", "#AB47BC", "#6A1B9A", "#1A0030"],
    minLabel: "ชนบท",
    maxLabel: "เมือง",
  },
  {
    id: "median_age",
    label: "อายุมัธยฐาน",
    chipClass: "chip-age",
    color: "#F48FB1",
    gradientColors: ["#F3E5F5", "#F48FB1", "#E91E63", "#880E4F", "#2D0016"],
    minLabel: "15 ปี",
    maxLabel: "50 ปี",
  },
  {
    id: "literacy",
    label: "อัตราการรู้หนังสือ",
    chipClass: "chip-literacy",
    color: "#26A69A",
    gradientColors: ["#880E4F", "#E91E63", "#FFB300", "#26A69A", "#004D40"],
    minLabel: "0%",
    maxLabel: "100%",
  },
  {
    id: "life_expectancy",
    label: "อายุขัยเฉลี่ย",
    chipClass: "chip-life",
    color: "#00C853",
    gradientColors: ["#B71C1C", "#FF5722", "#FFC107", "#00C853", "#1B5E20"],
    minLabel: "40 ปี",
    maxLabel: "90 ปี",
  },
  {
    id: "internet_access",
    label: "การเข้าถึงอินเทอร์เน็ต",
    chipClass: "chip-internet",
    color: "#00B0FF",
    gradientColors: ["#1A0A3D", "#3A0CA3", "#4361EE", "#00B0FF", "#E0F7FA"],
    minLabel: "0%",
    maxLabel: "100%",
  },
  {
    id: "bangkok_density",
    label: "ความหนาแน่นชุมชนแออัดกรุงเทพฯ",
    chipClass: "chip-bangkok-density",
    color: "#FF5C7A",
    gradientColors: ["#4ADE80", "#FACC15", "#FB923C", "#EF4444"],
    minLabel: "ต่ำ",
    maxLabel: "สูง",
  },
  // Economy
  {
    id: "gdp",
    label: "GDP ต่อหัว",
    chipClass: "chip-gdp",
    color: "#F2C94C",
    gradientColors: ["#1A2B0A", "#2E5C1A", "#38B56A", "#C8E63A", "#F2C94C"],
    minLabel: "$500",
    maxLabel: "$80,000+",
  },
  {
    id: "unemployment",
    label: "การว่างงาน",
    chipClass: "chip-unemployment",
    color: "#FF7043",
    gradientColors: ["#E8F5E9", "#A5D6A7", "#FFB300", "#FF7043", "#B71C1C"],
    minLabel: "0%",
    maxLabel: "30%+",
  },
  {
    id: "gini",
    label: "ความเหลื่อมล้ำรายได้",
    chipClass: "chip-gini",
    color: "#CE93D8",
    gradientColors: ["#004D40", "#00897B", "#F9A825", "#CE93D8", "#4A148C"],
    minLabel: "เท่ากัน",
    maxLabel: "ห่างกันมาก",
  },
  {
    id: "tourism",
    label: "รายได้จากการท่องเที่ยว",
    chipClass: "chip-tourism",
    color: "#FFD54F",
    gradientColors: ["#1A237E", "#3949AB", "#7986CB", "#FFD54F", "#FF6F00"],
    minLabel: "ต่ำ",
    maxLabel: "สูง",
  },
  // Energy & Resources
  {
    id: "electricity_access",
    label: "การเข้าถึงไฟฟ้า",
    chipClass: "chip-electricity",
    color: "#FFEE58",
    gradientColors: ["#212121", "#424242", "#FFF176", "#FFEE58", "#F57F17"],
    minLabel: "0%",
    maxLabel: "100%",
  },
  {
    id: "renewable_energy",
    label: "พลังงานหมุนเวียน",
    chipClass: "chip-renewable",
    color: "#69F0AE",
    gradientColors: ["#4E342E", "#8D6E63", "#AED581", "#69F0AE", "#00BFA5"],
    minLabel: "0%",
    maxLabel: "100%",
  },
  {
    id: "water_stress",
    label: "ความเครียดน้ำ",
    chipClass: "chip-water",
    color: "#29B6F6",
    gradientColors: ["#0D47A1", "#29B6F6", "#B3E5FC", "#FFCC02", "#BF360C"],
    minLabel: "ต่ำ",
    maxLabel: "รุนแรง",
  },
  {
    id: "crop_yield",
    label: "ผลผลิตพืชผล",
    chipClass: "chip-crop",
    color: "#C6E422",
    gradientColors: ["#5D4037", "#8D6E63", "#C8A97E", "#C6E422", "#33691E"],
    minLabel: "ต่ำ",
    maxLabel: "สูง",
  },
  // Health
  {
    id: "pollution",
    label: "มลพิษทางอากาศ (PM2.5)",
    chipClass: "chip-pollution",
    color: "#8B6CFF",
    gradientColors: ["#1A0A3D", "#5B3099", "#8B6CFF", "#C084FC", "#F5D0FE"],
    minLabel: "สะอาด",
    maxLabel: "อันตราย",
  },
  {
    id: "co2",
    label: "การปล่อย CO₂",
    chipClass: "chip-co2",
    color: "#78909C",
    gradientColors: ["#E8F5E9", "#A5D6A7", "#78909C", "#455A64", "#263238"],
    minLabel: "ต่ำ",
    maxLabel: "สูง",
  },
  {
    id: "healthcare",
    label: "การเข้าถึงการรักษาพยาบาล",
    chipClass: "chip-healthcare",
    color: "#EF9A9A",
    gradientColors: ["#B71C1C", "#E57373", "#EF9A9A", "#F8BBD0", "#FAFAFA"],
    minLabel: "จำกัด",
    maxLabel: "ทั่วถึง",
  },
  {
    id: "heat-risk",
    label: "ความเสี่ยงจากความร้อน",
    chipClass: "chip-heat-risk",
    color: "#E25A5A",
    gradientColors: ["#2E7D32", "#F2C94C", "#FF8A3D", "#B71C1C"],
    minLabel: "ต่ำ",
    maxLabel: "วิกฤต",
  },
  // Satellite
  {
    id: "lights",
    label: "แสงกลางคืน",
    chipClass: "chip-lights",
    color: "#7B61FF",
    gradientColors: ["#050709", "#1A1A2E", "#7B61FF", "#F2C94C", "#FFFDE7"],
    minLabel: "ไม่มีคนอยู่",
    maxLabel: "เมืองหนาแน่น",
  },
  {
    id: "vegetation",
    label: "พืชพรรณ (NDVI)",
    chipClass: "chip-vegetation",
    color: "#76FF03",
    gradientColors: ["#5D4037", "#BF360C", "#F9A825", "#76FF03", "#1B5E20"],
    minLabel: "โล่ง",
    maxLabel: "หนาแน่น",
  },
  {
    id: "cloud_cover",
    label: "ปกคลุมด้วยเมฆ",
    chipClass: "chip-cloud",
    color: "#E0E0E0",
    gradientColors: ["#1565C0", "#64B5F6", "#B3E5FC", "#E0E0E0", "#FAFAFA"],
    minLabel: "แจ่มใส",
    maxLabel: "เมฆหนา",
  },
];

const layerById = Object.fromEntries(
  ALL_LAYERS.map((l) => [l.id, l]),
) as Record<string, LayerConfig>;

export function getLayer(id: string): LayerConfig | undefined {
  return layerById[id];
}

export const LAYER_CATEGORIES: LayerCategory[] = [
  {
    id: "base",
    label: "ฐาน",
    // "blank" is excluded here — it lives as the permanent "None" row in the panel
    layers: ["terrain", "elevation"].map((id) => layerById[id]),
  },
  {
    id: "environment",
    label: "สิ่งแวดล้อม",
    layers: [
      "rainfall",
      "temperature",
      "humidity",
      "wind_speed",
      "sea_level_risk",
      "wildfire",
      "deforestation",
      "soil_quality",
    ].map((id) => layerById[id]),
  },
  {
    id: "demographics",
    label: "ประชากร",
    layers: [
      "population",
      "urban_rural",
      "median_age",
      "literacy",
      "life_expectancy",
      "internet_access",
      "bangkok_density",
    ].map((id) => layerById[id]),
  },
  {
    id: "economy",
    label: "เศรษฐกิจ",
    layers: ["gdp", "unemployment", "gini", "tourism"].map(
      (id) => layerById[id],
    ),
  },
  {
    id: "energy",
    label: "พลังงานและทรัพยากร",
    layers: [
      "electricity_access",
      "renewable_energy",
      "water_stress",
      "crop_yield",
    ].map((id) => layerById[id]),
  },
  {
    id: "health",
    label: "สุขภาพ",
    layers: ["pollution", "co2", "healthcare"].map((id) => layerById[id]),
  },
  {
    id: "satellite",
    label: "ดาวเทียม",
    layers: ["lights", "vegetation", "cloud_cover"].map((id) => layerById[id]),
  },
];

// Keep LAYERS export for backward compat (ColorLegend etc)
export const LAYERS = ALL_LAYERS;
