/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const HeatRiskAreaId = IDL.Nat;
export const Time = IDL.Int;
export const HeatRiskArea = IDL.Record({
  'id' : HeatRiskAreaId,
  'communityDensityFactor' : IDL.Float64,
  'baseTemp' : IDL.Float64,
  'latitude' : IDL.Float64,
  'title' : IDL.Text,
  'apparentTemp' : IDL.Float64,
  'createdAt' : Time,
  'recommendedGreenArea' : IDL.Float64,
  'vegetationFactor' : IDL.Float64,
  'recommendedShelters' : IDL.Nat,
  'longitude' : IDL.Float64,
  'buildingFactor' : IDL.Float64,
  'radiusMeters' : IDL.Float64,
  'riskLevel' : IDL.Text,
  'riskScore' : IDL.Nat,
});
export const PinId = IDL.Nat;
export const Pin = IDL.Record({
  'id' : PinId,
  'latitude' : IDL.Float64,
  'title' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'longitude' : IDL.Float64,
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const HeatRiskAreaInput = IDL.Record({
  'communityDensityFactor' : IDL.Opt(IDL.Float64),
  'latitude' : IDL.Float64,
  'title' : IDL.Text,
  'longitude' : IDL.Float64,
  'radiusMeters' : IDL.Float64,
});
export const PinInput = IDL.Record({
  'latitude' : IDL.Float64,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'longitude' : IDL.Float64,
});
export const GovDataPoint = IDL.Record({
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'value' : IDL.Float64,
  'source' : IDL.Text,
  'name' : IDL.Text,
});
export const GovDataResponse = IDL.Record({
  'fetchedAt' : IDL.Int,
  'source' : IDL.Text,
  'error' : IDL.Text,
  'success' : IDL.Bool,
  'points' : IDL.Vec(GovDataPoint),
});
export const BBox = IDL.Record({
  'minLat' : IDL.Float64,
  'minLng' : IDL.Float64,
  'maxLat' : IDL.Float64,
  'maxLng' : IDL.Float64,
});
export const WildfirePoint = IDL.Record({
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'satellite' : IDL.Text,
  'brightness' : IDL.Float64,
  'acqDate' : IDL.Text,
  'confidence' : IDL.Nat,
});
export const WildfireResponse = IDL.Record({
  'fires' : IDL.Vec(WildfirePoint),
});
export const GeocodePlace = IDL.Record({
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'country' : IDL.Text,
  'name' : IDL.Text,
});
export const GeocodeResult = IDL.Record({
  'rawJson' : IDL.Text,
  'results' : IDL.Vec(GeocodePlace),
});
export const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
export const HttpRequestResult = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : HttpRequestResult,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});

export const idlService = IDL.Service({
  '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__heatRiskAreas' : IDL.Func(
      [IDL.Opt(HeatRiskAreaId), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(HeatRiskAreaId, HeatRiskArea))],
      ['query'],
    ),
  '__heatRiskIdCounter' : IDL.Func([], [IDL.Reserved], ['query']),
  '__idCounter' : IDL.Func([], [IDL.Reserved], ['query']),
  '__pins' : IDL.Func(
      [IDL.Opt(PinId), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(PinId, Pin))],
      ['query'],
    ),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createHeatRiskArea' : IDL.Func(
      [
        HeatRiskAreaInput,
        IDL.Nat,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        IDL.Nat,
        IDL.Float64,
        IDL.Opt(IDL.Float64),
      ],
      [HeatRiskAreaId],
      [],
    ),
  'createPin' : IDL.Func([PinInput], [PinId], []),
  'deleteHeatRiskArea' : IDL.Func([HeatRiskAreaId], [], []),
  'deletePin' : IDL.Func([PinId], [], []),
  'fetchGovData' : IDL.Func([IDL.Text], [GovDataResponse], []),
  'fetchWildfireData' : IDL.Func([BBox], [WildfireResponse], []),
  'geocodeSearch' : IDL.Func([IDL.Text], [GeocodeResult], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listHeatRiskAreas' : IDL.Func([], [IDL.Vec(HeatRiskArea)], ['query']),
  'listPins' : IDL.Func([], [IDL.Vec(Pin)], ['query']),
  'readHeatRiskArea' : IDL.Func(
      [HeatRiskAreaId],
      [IDL.Opt(HeatRiskArea)],
      ['query'],
    ),
  'readPin' : IDL.Func([PinId], [Pin], ['query']),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateHeatRiskArea' : IDL.Func(
      [
        HeatRiskAreaId,
        HeatRiskAreaInput,
        IDL.Nat,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        IDL.Nat,
        IDL.Float64,
        IDL.Opt(IDL.Float64),
      ],
      [],
      [],
    ),
  'updatePin' : IDL.Func([PinId, PinInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const HeatRiskAreaId = IDL.Nat;
  const Time = IDL.Int;
  const HeatRiskArea = IDL.Record({
    'id' : HeatRiskAreaId,
    'communityDensityFactor' : IDL.Float64,
    'baseTemp' : IDL.Float64,
    'latitude' : IDL.Float64,
    'title' : IDL.Text,
    'apparentTemp' : IDL.Float64,
    'createdAt' : Time,
    'recommendedGreenArea' : IDL.Float64,
    'vegetationFactor' : IDL.Float64,
    'recommendedShelters' : IDL.Nat,
    'longitude' : IDL.Float64,
    'buildingFactor' : IDL.Float64,
    'radiusMeters' : IDL.Float64,
    'riskLevel' : IDL.Text,
    'riskScore' : IDL.Nat,
  });
  const PinId = IDL.Nat;
  const Pin = IDL.Record({
    'id' : PinId,
    'latitude' : IDL.Float64,
    'title' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'longitude' : IDL.Float64,
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const HeatRiskAreaInput = IDL.Record({
    'communityDensityFactor' : IDL.Opt(IDL.Float64),
    'latitude' : IDL.Float64,
    'title' : IDL.Text,
    'longitude' : IDL.Float64,
    'radiusMeters' : IDL.Float64,
  });
  const PinInput = IDL.Record({
    'latitude' : IDL.Float64,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'longitude' : IDL.Float64,
  });
  const GovDataPoint = IDL.Record({
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'value' : IDL.Float64,
    'source' : IDL.Text,
    'name' : IDL.Text,
  });
  const GovDataResponse = IDL.Record({
    'fetchedAt' : IDL.Int,
    'source' : IDL.Text,
    'error' : IDL.Text,
    'success' : IDL.Bool,
    'points' : IDL.Vec(GovDataPoint),
  });
  const BBox = IDL.Record({
    'minLat' : IDL.Float64,
    'minLng' : IDL.Float64,
    'maxLat' : IDL.Float64,
    'maxLng' : IDL.Float64,
  });
  const WildfirePoint = IDL.Record({
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'satellite' : IDL.Text,
    'brightness' : IDL.Float64,
    'acqDate' : IDL.Text,
    'confidence' : IDL.Nat,
  });
  const WildfireResponse = IDL.Record({ 'fires' : IDL.Vec(WildfirePoint) });
  const GeocodePlace = IDL.Record({
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'country' : IDL.Text,
    'name' : IDL.Text,
  });
  const GeocodeResult = IDL.Record({
    'rawJson' : IDL.Text,
    'results' : IDL.Vec(GeocodePlace),
  });
  const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const HttpRequestResult = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : HttpRequestResult,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  
  return IDL.Service({
    '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__heatRiskAreas' : IDL.Func(
        [IDL.Opt(HeatRiskAreaId), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(HeatRiskAreaId, HeatRiskArea))],
        ['query'],
      ),
    '__heatRiskIdCounter' : IDL.Func([], [IDL.Reserved], ['query']),
    '__idCounter' : IDL.Func([], [IDL.Reserved], ['query']),
    '__pins' : IDL.Func(
        [IDL.Opt(PinId), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(PinId, Pin))],
        ['query'],
      ),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createHeatRiskArea' : IDL.Func(
        [
          HeatRiskAreaInput,
          IDL.Nat,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          IDL.Nat,
          IDL.Float64,
          IDL.Opt(IDL.Float64),
        ],
        [HeatRiskAreaId],
        [],
      ),
    'createPin' : IDL.Func([PinInput], [PinId], []),
    'deleteHeatRiskArea' : IDL.Func([HeatRiskAreaId], [], []),
    'deletePin' : IDL.Func([PinId], [], []),
    'fetchGovData' : IDL.Func([IDL.Text], [GovDataResponse], []),
    'fetchWildfireData' : IDL.Func([BBox], [WildfireResponse], []),
    'geocodeSearch' : IDL.Func([IDL.Text], [GeocodeResult], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listHeatRiskAreas' : IDL.Func([], [IDL.Vec(HeatRiskArea)], ['query']),
    'listPins' : IDL.Func([], [IDL.Vec(Pin)], ['query']),
    'readHeatRiskArea' : IDL.Func(
        [HeatRiskAreaId],
        [IDL.Opt(HeatRiskArea)],
        ['query'],
      ),
    'readPin' : IDL.Func([PinId], [Pin], ['query']),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateHeatRiskArea' : IDL.Func(
        [
          HeatRiskAreaId,
          HeatRiskAreaInput,
          IDL.Nat,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          IDL.Nat,
          IDL.Float64,
          IDL.Opt(IDL.Float64),
        ],
        [],
        [],
      ),
    'updatePin' : IDL.Func([PinId, PinInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };