/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BBox {
  'minLat' : number,
  'minLng' : number,
  'maxLat' : number,
  'maxLng' : number,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface GeocodePlace {
  'lat' : number,
  'lng' : number,
  'country' : string,
  'name' : string,
}
export interface GeocodeResult {
  'rawJson' : string,
  'results' : Array<GeocodePlace>,
}
export interface GovDataPoint {
  'lat' : number,
  'lng' : number,
  'value' : number,
  'source' : string,
  'name' : string,
}
export interface GovDataResponse {
  'fetchedAt' : bigint,
  'source' : string,
  'error' : string,
  'success' : boolean,
  'points' : Array<GovDataPoint>,
}
export interface HeatRiskArea {
  'id' : HeatRiskAreaId,
  'communityDensityFactor' : number,
  'baseTemp' : number,
  'latitude' : number,
  'title' : string,
  'apparentTemp' : number,
  'createdAt' : Time,
  'recommendedGreenArea' : number,
  'vegetationFactor' : number,
  'recommendedShelters' : bigint,
  'longitude' : number,
  'buildingFactor' : number,
  'radiusMeters' : number,
  'riskLevel' : string,
  'riskScore' : bigint,
}
export type HeatRiskAreaId = bigint;
export interface HeatRiskAreaInput {
  'communityDensityFactor' : [] | [number],
  'latitude' : number,
  'title' : string,
  'longitude' : number,
  'radiusMeters' : number,
}
export interface HttpHeader { 'value' : string, 'name' : string }
export interface HttpRequestResult {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export interface Pin {
  'id' : PinId,
  'latitude' : number,
  'title' : string,
  'createdAt' : Time,
  'description' : string,
  'longitude' : number,
}
export type PinId = bigint;
export interface PinInput {
  'latitude' : number,
  'title' : string,
  'description' : string,
  'longitude' : number,
}
export type Result = { 'ok' : null } |
  { 'err' : Error };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : HttpRequestResult,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WildfirePoint {
  'lat' : number,
  'lng' : number,
  'satellite' : string,
  'brightness' : number,
  'acqDate' : string,
  'confidence' : bigint,
}
export interface WildfireResponse { 'fires' : Array<WildfirePoint> }
export interface _SERVICE {
  '__accessControlState' : ActorMethod<[], any>,
  '__heatRiskAreas' : ActorMethod<
    [[] | [HeatRiskAreaId], [] | [bigint]],
    Array<[HeatRiskAreaId, HeatRiskArea]>
  >,
  '__heatRiskIdCounter' : ActorMethod<[], any>,
  '__idCounter' : ActorMethod<[], any>,
  '__pins' : ActorMethod<[[] | [PinId], [] | [bigint]], Array<[PinId, Pin]>>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createHeatRiskArea' : ActorMethod<
    [
      HeatRiskAreaInput,
      bigint,
      number,
      number,
      number,
      number,
      string,
      bigint,
      number,
      [] | [number],
    ],
    HeatRiskAreaId
  >,
  'createPin' : ActorMethod<[PinInput], PinId>,
  'deleteHeatRiskArea' : ActorMethod<[HeatRiskAreaId], undefined>,
  'deletePin' : ActorMethod<[PinId], undefined>,
  'fetchGovData' : ActorMethod<[string], GovDataResponse>,
  'fetchWildfireData' : ActorMethod<[BBox], WildfireResponse>,
  'geocodeSearch' : ActorMethod<[string], GeocodeResult>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listHeatRiskAreas' : ActorMethod<[], Array<HeatRiskArea>>,
  'listPins' : ActorMethod<[], Array<Pin>>,
  'readHeatRiskArea' : ActorMethod<[HeatRiskAreaId], [] | [HeatRiskArea]>,
  'readPin' : ActorMethod<[PinId], Pin>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateHeatRiskArea' : ActorMethod<
    [
      HeatRiskAreaId,
      HeatRiskAreaInput,
      bigint,
      number,
      number,
      number,
      number,
      string,
      bigint,
      number,
      [] | [number],
    ],
    undefined
  >,
  'updatePin' : ActorMethod<[PinId, PinInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];